name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-next-gql:
    uses: enalmada/.github/.github/workflows/run-tests.yml@main
    with:
      working-directory: 'packages/next-gql'

  tests-next-gql-codegen:
    uses: enalmada/.github/.github/workflows/run-tests.yml@main
    with:
      working-directory: 'packages/next-gql-codegen'
